packages:
  - models
  - packages/*
  - apps/*
allowBuilds:
  core-js-pure: false
  esbuild: true
  hyperliquid: false
  simple-git-hooks: false
  workerd: true
patchedDependencies:
  tau-prolog@0.3.4: patches/tau-prolog@0.3.4.patch
