import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const sourceFiles = ["math.pl", "series.pl", "indicators.pl"];
const sections = await Promise.all(
  sourceFiles.map(async (filename) => {
    const source = await readFile(join(packageRoot, "prolog", filename), "utf8");
    return `% ${filename}\n${source.trim()}\n`;
  }),
);
const prolog = sections.join("\n");
const generated = `// Generated by scripts/embed-prolog.mjs. Do not edit.\nexport const PROLOG_SOURCE = ${JSON.stringify(prolog)};\n`;
const outputPath = join(packageRoot, "src", "prolog-source.ts");

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== generated) {
    process.stderr.write("Embedded Prolog source is stale. Run pnpm prepare:prolog.\n");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, generated, "utf8");
}

